baseURL = "https://feuille-de-chou.netlify.app/"
defaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = "ja"
theme = "hugo-theme-texify"
title = "白象の宴"

pygmentsUseClasses = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[menu]
    [[menu.main]]
        identifier = "jjmo"
        name = "JJMO"
        url = "/JJMO/toc"
        weight = 1
    [[menu.main]]
        identifier = "jmo"
        name = "JMO"
        url = "/JMO/toc"
        weight = 2
    [[menu.main]]
        identifier = "imo"
        name = "IMO"
        url = "/IMO/toc"
        weight = 3

[params]
  enable_mathjax = true
  
[minify]
 disableJSON = true