baseURL = "https://feuille-de-chou.netlify.app/"
defaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = "ja"
theme = "hugo-theme-texify"
title = "白象の宴"

pygmentsUseClasses = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[menu]
    [[menu.main]]
        identifier = "math"
        name = "数学"
        url = "/math/toc"
        weight = 1
    [[menu.main]]
        identifier = "physics"
        name = "物理"
        url = "/physics/toc"
        weight = 2
    [[menu.main]]
        identifier = "cs"
        name = "情報"
        url = "/cs/toc"
        weight = 3

[params]
  enable_mathjax = true
  
[minify]
 disableJSON = true